routes/backend.php
<?php

use App\Media;
use Illuminate\Support\Collection;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //print_r(Media::get()->all());

    return view('backend.dashboard');
})->name('dashboard');

Route::resource('attribute', 'AttributeController');

Route::resource('product', 'ProductController');

Route::get('/remark', function () {
    return view('backend.remark');
});

Route::get('/data', function(){

    echo "<pre>";
	$attributeGroups = \App\AttributeGroup::all();
	foreach ($attributeGroups as $attributeGroup) {
		$attributeGroup->setRelation('attributes', $attributeGroup->attributes->keyBy('id'));
	}

    $attributes = new \App\Attribute();
    $attributes = $attributes->without($attributes->excluded_attributes)->keyBy('id');

    print_r($attributeGroups->toArray());

    print_r($attributes->toArray());
});


Route::resource('order', 'OrderController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/recom', 'RecommendationController@index')->name('recommendation');

app/Attribute.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Attribute extends Model
{
    //
    public $excluded_attributes = [2,3,4,5];

    public $timestamps = false;

    public function products(){
    	return $this->belongsToMany('App\Product', 'product_attributes');
    }

    public function groups(){
    	return $this->belongsToMany('App\AttributeGroup', 'attribute_group_pivots');
    }

    public function options(){
    	return $this->hasMany('App\AttributeOption', 'attribute_id');
    }
    public function productOptions($product_id){
        return $this->options->where('product_id', $product_id);
    }
    public function without($ids){
        return $this->whereNotIn('id', $ids)->get();
    }
}

app/Http/Controllers/Backend/AttributeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Attribute;
use Validator;

class AttributeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = Attribute::all();

        return view('backend.attribute.index', ['model' => $model]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.attribute.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        if (!isset($request->slug)) {
            $request->request->set('slug',str_slug($request->name, "-"));
        }

        $request->validate([
            'name' => 'required',
            'slug' => 'required|unique:attributes,slug',
            'type' => 'required'
        ]);

        $model = new Attribute;
        $model->name = $request->name;
        $model->slug = $request->slug;
        $model->type = $request->type;
        $model->description = $request->description;


        if ($model->save()) {
            route('attribute.index');
        }else{
            die;
            print_r($model->error());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
<<<<<<< HEAD
use App\Order;
=======
>>>>>>> master

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
<<<<<<< HEAD
        $orders = Order::all();
        $products = Product::all();
        return view('backend.order.index', [
            'orders' => $orders,
            'products' => $products,
            ]);
=======
        //
>>>>>>> master
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::orderBy('year','asc')->get();
        return view('backend.order.create', ['products' => $products]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $products = $request->input('products');


        $order = new \App\Order();
        $order->note = "manualy input";
        if ($order->save()) {
            foreach ($products as $product_id) {
                $product_order = new \App\OrderProduct();
                $product_order->order_id = $order->id;
                $product_order->product_id = $product_id;

                $product_order->save();
            }
        }

        return redirect('backend/order/create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\AttributeGroup;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Backend.product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $attributeGroups = \App\AttributeGroup::all();
        foreach ($attributeGroups as $attributeGroup) {
            $attributeGroup->setRelation('attributes', $attributeGroup->attributes->keyBy('id'));
        }

        $attributes = new \App\Attribute();
        $attributes = $attributes->without($attributes->excluded_attributes)->keyBy('id');
        
        return view('Backend.product.create',[
            'attributeGroups' => $attributeGroups->toJson(),
            'attributes' => $attributes->toJson()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        //
    }
}

resources/views/backend/attribute/_form.blade.php
<div class="m-portlet__body">

	<br>

	<div class="m-form__content">
		<div class="m-alert m-alert--icon alert alert-danger m--hide" role="alert" id="form-alert">
			<div class="m-alert__icon">
				<i class="la la-warning"></i>
			</div>
			<div class="m-alert__text">
				Oh snap! Check a few things up and try submitting again.
			</div>
			<div class="m-alert__close">
				<button type="button" class="close" data-close="alert" aria-label="Close"></button>
			</div>
		</div>
	</div>

	@if ($errors->any())
	    <div class="m-form__content">
			<div class="m-alert m-alert--icon alert alert-danger" role="alert" id="form-alert">
				<div class="m-alert__icon">
					<i class="la la-warning"></i>
				</div>
				<div class="m-alert__text">
					<ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
				</div>
				<div class="m-alert__close">
					<button type="button" class="close" data-close="alert" aria-label="Close"></button>
				</div>
			</div>
		</div>
	@endif

	<div class="form-group m-form__group">
		<label for="name">
			Name
		</label>
		<input type="text" name="name" id="name" class="form-control m-input" value="{{ old('name') }}">
	</div>

	<div class="form-group m-form__group">
		<label for="slug">
			Slug
		</label>
		<input type="text" name="slug" id="slug" class="form-control m-input" value="{{ old('slug') }}">
	</div>

	<div class="form-group m-form__group">
		<label for="type">
			Type
		</label>
		<select type="text" name="type" id="type" class="form-control m-input">
			<option value="text">Text</option>
			<option value="textarea">Textarea</option>
		</select>
	</div>

	<div class="form-group m-form__group">
		<label for="description">
			Description
		</label>
		<textarea name="description" id="description" class="form-control m-input" rows="4">{{ old('description') }}</textarea>
	</div>

</div>
<div class="m-portlet__foot m-portlet__foot--fit">
	<div class="m-form__actions">
		<button type="submit" class="btn btn-primary">
			Submit
		</button>
		<button type="reset" class="btn btn-secondary">
			Cancel
		</button>
	</div>
</div>

@section('scripts')
<script type="text/javascript">
	//== Class definition

var FormControls = function () {
    //== Private functions
    
    var formValidation = function () {
        
    }
    return {
        // public functions
        init: function() {
            formValidation(); 
        }
    };
}();

jQuery(document).ready(function() {    
    $( "#form" ).validate({
        // define validation rules
        rules: {
            name: {
                required: true
            },
        },
        
        //display error alert on form submit  
        invalidHandler: function(event, validator) {     
            var alert = $('#form-alert');
            alert.removeClass('m--hide').show();
            mApp.scrollTo(alert, -200);
        },

        submitHandler: function (form) {
            form[0].submit(); // submit the form
        }
    });
});
</script>

@endsection

resources/views/backend/attribute/create.blade.php
<?php $active_nav = 'product-add'; ?>

@extends('backend.layout')

@section('active_product-list', 'm-menu__item--active')

@section('title', 'Add New Product')

@section('breadcumb')

<li class="m-nav__separator">
	-
</li>
<li class="m-nav__item">
	<a href="" class="m-nav__link">
		<span class="m-nav__link-text">
			Product
		</span>
	</a>
</li>
<li class="m-nav__separator">
	-
</li>
<li class="m-nav__item">
	<a href="" class="m-nav__link">
		<span class="m-nav__link-text">
			@yield('title')
		</span>
	</a>
</li>
@endsection

@section('content')
	<div class="m-portlet">
		<!--begin::Form-->
		
		<form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed" id="form" novalidate="novalidate" method="POST" action="{{	route('attribute.store') }}">
			{{ csrf_field() }}
			
			@include('backend.attribute._form')
		</form>
		<!--end::Form-->
	</div>
@endsection

resources/views/backend/attribute/index.blade.php
<?php $active_nav = 'product-list'; ?>

@extends('backend.layout')

@section('active_product-list', 'm-menu__item--active')

@section('title', 'Product Lists')

@section('content')
	<div class="m-portlet m-portlet--tab">

        <table class="table table-striped m-table m-table--head-bg-success">
            <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Slug</th>
                <th>Description</th>
                <th colspan="3">Action</th>
            </tr>
            </thead>

            @foreach ($model as $attribute)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$attribute->name}}</td>
                    <td>{{$attribute->slug}}</td>
                    <td>{{$attribute->description}}</td>
                    <td style="overflow: visible; width: 120px;">
                        <!-- <a href="#" class="btn btn-sm btn-outline-success m-btn m-btn--icon m-btn--icon-only" title="View"><i class="fa fa-eye"></i></a> -->
                        <a href="{{ route('attribute.edit', ['id' => $attribute->id]) }}" class="btn btn-sm btn-outline-accent m-btn m-btn--icon m-btn--icon-only" title="Edit"><i class="fa fa-edit"></i></a>
                        <a href="#" class="btn btn-sm btn-outline-danger m-btn m-btn--icon m-btn--icon-only" title="Delete"><i class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            @endforeach
        </table>
	</div>
@endsection